apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata: # kpt-merge: /my-gateway-class
  name: my-gateway-class
  annotations:
    internal.kpt.dev/upstream-identifier: 'gateway.networking.k8s.io|GatewayClass|default|my-gateway-class'
spec:
  controllerName: traefik.io/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata: # kpt-merge: default/my-gateway
  name: my-gateway
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: 'gateway.networking.k8s.io|Gateway|default|my-gateway'
spec:
  gatewayClassName: my-gateway-class
  listeners: # Use GatewayClass defaults for listener definition.
    - name: http
      protocol: HTTP
      port: 80
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        certificateRefs:
          - kind: Secret
            name: mysecret
    - name: tcp
      protocol: TCP
      port: 9000
      allowedRoutes:
        kinds:
          - kind: TCPRoute
    - name: tls
      protocol: TLS
      port: 9443
      hostname: example.com
      tls:
        certificateRefs:
          - kind: Secret
            name: mysecret
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata: # kpt-merge: default/http-app
  name: http-app
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: 'gateway.networking.k8s.io|HTTPRoute|default|http-app'
spec:
  parentRefs:
    - name: my-gateway
  hostnames:
    - foo.com
  rules:
    - matches:
        - path:
            type: Exact
            value: /bar
      backendRefs:
        - name: whoami
          port: 80
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /foo
      backendRefs:
        - group: traefik.io
          kind: TraefikService
          name: myservice@file
          weight: 1
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata: # kpt-merge: default/tcp-app
  name: tcp-app
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: 'gateway.networking.k8s.io|TCPRoute|default|tcp-app'
spec:
  parentRefs:
    - name: my-gateway
  rules:
    - backendRefs:
        - name: whoamitcp
          port: 9000
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata: # kpt-merge: default/tls-app
  name: tls-app
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: 'gateway.networking.k8s.io|TLSRoute|default|tls-app'
spec:
  parentRefs:
    - name: my-gateway
      sectionName: tls
  rules:
    - backendRefs:
        - name: whoamitcp
          port: 9000
          weight: 1
